#define DEF_KICKASSCOIN_VERSION_TAG "889dda60c"
#define DEF_KICKASSCOIN_VERSION "0.0.1.0"
#define DEF_KICKASSCOIN_RELEASE_NAME "maggot eggs"
#define DEF_KICKASSCOIN_VERSION_FULL DEF_KICKASSCOIN_VERSION "-" DEF_KICKASSCOIN_VERSION_TAG

#include "version.h"

const char* const KICKASSCOIN_VERSION_TAG = DEF_KICKASSCOIN_VERSION_TAG;
const char* const KICKASSCOIN_VERSION = DEF_KICKASSCOIN_VERSION;
const char* const KICKASSCOIN_RELEASE_NAME = DEF_KICKASSCOIN_RELEASE_NAME;
const char* const KICKASSCOIN_VERSION_FULL = DEF_KICKASSCOIN_VERSION_FULL;
